local foods = {}

-- INGREDIENTS
foods.common_ingredients = {["Flour"] 			= true,
							["Salt"] 			= true,
							["Black pepper"] 	= true,
							["Cheese"] 			= true,
							["Milk"] 			= true,
							["Eggs"] 			= true,
							["Olive oil"] 		= true,
							["Vegetable oil"] 	= true,
							["Potato"] 			= true,
							["Sugar"]			= true,
							["Brown Sugar"]		= true,
							["Honey"] 			= true,
							["Baking Powder"]	= true,
							["Baking Soda"]		= true,
							["Water"]			= true}

foods.meats = {				["Chicken breasts"] = true,
				  			["Chicken legs"] 	= true,
							["Chicken thighs"] 	= true,
							["Chicken wings"]	= true,
							["Chicken - whole"] = true,
							["Lamb"]	 		= true,
							["Beef"]	 		= true,
							["Steak"]  			= true,
							["Pork sausage"]	= true,
							["Chicken sausage"] = true,
							["Turkey sausage"] 	= true,
							["Pork loins"]		= true,
							["Pork chops"] 		= true,
							['Shrimp']			= true,
							['Shrimp - jumbo']  = true,
							['Scallops'] 		= true,
							['Fish']			= true,
							['Ham'] 			= true}

foods.fruits_and_veggies = {["Broccoli"] 		= true,
							["Carrots"] 		= true,
							["Apples"]			= true,
							["Strawberries"]	= true,
							["Celery"]	 		= true,
							["Cabbage"]  		= true,
							["Lettuce"] 		= true,
							["Tomato"]			= true,
							["Pumpkin"]			= true,
							["Potato"]			= true,
							["Eggplant"]		= true,
							["Butternut squash"] = true,
							["Zuchinni squash"]	 = true,
							["Beets"] 			= true,
							["Spinnach"]		= true,
							["Chick peas"]		= true,
							["Red beans"]		= true,
							["Black beans"]		= true,
							["Baked beans"] 	= true,
							["Green beans"] 	= true,
							["Peaches"] 		= true,
							["Plums"] 			= true,
							["Cherries"]		= true,
							["Pears"]			= true,
							["Raspberries"]		= true,
							["Blackberries"]	= true,
							["Onions"]			= true,
							["Cucumbers"]		= true,
							["Banana"] 			= true}

foods.starches =    {		["Potato"] 			= true,
							["Instant mashed potato"] = true,
							["Penne"] 			= true,
							["Linguini"] 		= true,
							["Macaroni"] 		= true,
							["White rice"] 		= true,
							["Brown rice"] 		= true,
							["Spaghetti"] 		= true,
							["Fettuccini"] 		= true}

foods.seasonings =  {		["Black Pepper"] 	= true,
							["Salt"]	 		= true,
							["Garlic powder"]	= true,
							["Onion powder"] 	= true,
							["Cinnamon"] 		= true,
							["Garlic cloves"] 	= true,
							["Minced Garlic"] 	= true,
							["All Purpose Seasoning"] = true,
							["Allspice"] 		= true,
							["Thyme"] 			= true,
							["Basil"] 			= true,
							["Oregano"] 		= true,
							["Parsley"] 		= true,
							["Bay Leaves"] 		= true}

foods.dairy = {				["Milk"] 			= true,
							["Almond Milk"]		= true,
							["Soy Milk"] 		= true,
							["Yoghurt"] 		= true,
							["Sour Cream"] 		= true,
							["Whipped Cream"] 	= true,
							["Half and Half"] 	= true,
							["Light Cream"] 	= true,
							["Heavy Cream"] 	= true,
							["Cheddar Cheese"] 	= true,
							["Gouda Cheese"]	= true,
							["Mozzarella Cheese"]= true,
							["Provolone Cheese"]= true,
							["Parmesan Cheese"] = true,
							["Ricotta Cheese"] 	= true,
							["PepperJack Cheese"] = true,
							["Cream Cheese"] 	= true,
							["Cheese"] 			= true,
							["Marscarpone Cheese"] =true,
							["Brie Cheese"] 	= true,
							["Blue Cheese"] 	= true,
							["Cottage Cheese"] 	= true,
							["Butter"]			= true,
							["Margarine"]		= true,
							["Ice Cream"]		= true}

foods.sauces = {			["Soy Sauce"] 		= true,
							["Ketchup"] 		= true,
							["Mustard"] 		= true,
							["Mayonnaise"]		= true,
							["Worcestershire Sauce"] = true,
							["BBQ Sauce"]		= true,
							["Honey BBQ Sauce"] = true,
							["Garlic Sauce"] 	= true}

foods.nuts = {				["Macadamia Nuts"] 	= true,
							["Pistachios"]		= true,
							["Cashews"]			= true,
							["Almonds"]			= true,
							["Pecans"]			= true,
							["Walnuts"]			= true,
							["Trail Mix"]		= true,
							}

return foods
